In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fredericobreno/play-tennis")

print("Path to dataset files:", path)

In [ ]:
# Problem 1
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

In [ ]:
# Solution

# P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes)

# P(No | Sunny,Hot,High,Weak)=P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No)

# Compare and decide using the Maximum a posteriori rule

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [72]:
df=pd.read_csv('play_tennis.csv')
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [73]:
df.shape

(14, 6)

In [37]:

# Problem 2

# Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak

# Play or No Play?

In [38]:
# Solution

# P(Yes | Overcast,Cold,Low,Weak)=P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes)

# P(No | Overcast,Cold,Low,Weak)=P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No)

# Compare and decide using the Maximum a posteriori rule

In [ ]:
# training
# in a training staage Naive bayes create a lookup table store in dictionatry datatyype it store the every data  
# testing

In [15]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [59]:
prob_yes=9/14
prob_no=5/14
print(f"prob_yes :{prob_yes} ; prob_no:{prob_no}")

prob_yes :0.6428571428571429 ; prob_no:0.35714285714285715

In [ ]:
# outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [61]:
# No
prob_overcast_no=0
prob_rain_no=2/5
prob_sunny_no=3/5
# Yes
prob_overcast_yes=4/9
prob_rain_yes=3/9
prob_sunny_yes=2/9

In [62]:
# temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [63]:
# No
prob_cool_no=1/5
prob_hot_no=2/5
prob_mild_no=2/5
# Yes
prob_cool_yes=3/9
prob_hot_yes=2/9
prob_mild_yes=4/9

In [64]:
# humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [65]:
# no
prob_high_no=4/5
prob_normal_no=1/5
# yes
prob_high_yes=3/9
prob_normal_yes=6/9

In [66]:
# wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [67]:
# no
prob_strong_no=3/5
prob_weak_no=2/5
# yes
# no
prob_strong_yes=3/9
prob_weak_yes=6/9

### We will solve problem statement 1 and you have to solve problem statement 2

In [68]:
# Problem 1
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

In [ ]:
prob_play_yes=prob_yes*prob_sunny_yes*prob_hot_yes*prob_high_yes*prob_weak_yes

prob_play_no=prob_no*prob_sunny_no*prob_hot_no*prob_high_no*prob_weak_no

In [70]:
prob_play_yes,prob_play_no

(0.007054673721340388, 0.02742857142857143)

In [71]:
# we get that prob_play_no > prob_play_yes
# there is no play