In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [2]:
df=pd.read_csv('cars.csv')
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [3]:
df['selling_price'].value_counts()

selling_price
300000     227
600000     213
350000     209
550000     204
450000     195
          ...
1516000      1
2575000      1
212000       1
2051000      1
313000       1
Name: count, Length: 677, dtype: int64

In [4]:
pd.get_dummies(df,columns=['owner','fuel'],drop_first=True)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,True,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,True
3,Hyundai,127000,225000,False,False,False,False,True,False,False
4,Maruti,120000,130000,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,True,False,False,False,True,False,False
8125,Maruti,120000,382000,False,False,False,False,True,False,False
8126,Tata,25000,290000,False,False,False,False,True,False,False
8127,Tata,25000,290000,False,False,False,False,True,False,False

In [5]:
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)
X_train.shape

(6502, 4)

In [12]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
X_train_new=ohe.fit_transform(X_train[['owner','fuel']])
X_test_new=ohe.transform(X_test[['owner','fuel']])
X_train_new

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int32)

In [44]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)