In [1]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
# from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
# from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv("titanic.csv")

In [3]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)
df

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
413         0       3    male   NaN      0      0    8.0500        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S
416         0       3    male   NaN      0      0    8.0500        S
417         0       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]

In [4]:
df.isnull().sum()
# df.head()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [16]:
df.fillna({"Age": df["Age"].mean()}, inplace=True)

In [5]:
df.isnull().sum()
df

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
413         0       3    male   NaN      0      0    8.0500        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S
416         0       3    male   NaN      0      0    8.0500        S
417         0       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns="Survived"),df['Survived'],test_size=0.2,random_state=42)
X_train.isnull().sum()

Pclass       0
Sex          0
Age         72
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [21]:
si_fare=SimpleImputer()
X_train_fare=si_fare.fit_transform(X_train[["Fare"]])
X_test_fare=si_fare.transform(X_test[["Fare"]])
X_train_fare

array([[ 13.        ],
       [ 31.5       ],
       [ 10.7083    ],
       [ 82.2667    ],
       [ 10.5       ],
       [  7.05      ],
       [ 26.        ],
       [ 21.075     ],
       [ 79.2       ],
       [  9.225     ],
       [  7.925     ],
       [ 46.9       ],
       [ 18.        ],
       [ 47.1       ],
       [  7.75      ],
       [ 12.35      ],
       [  7.775     ],
       [  7.75      ],
       [  7.05      ],
       [  8.6625    ],
       [  7.925     ],
       [ 25.4667    ],
       [  7.8958    ],
       [ 10.5       ],
       [  7.225     ],
       [  7.725     ],
       [  7.8958    ],
       [ 12.35      ],
       [ 14.5       ],
       [  0.        ],
       [134.5       ],
       [  6.4375    ],
       [ 61.9792    ],
       [ 29.        ],
       [ 27.75      ],
       [ 21.        ],
       [  8.7125    ],
       [ 26.        ],
       [  8.6625    ],
       [ 21.6792    ],
       [  7.8542    ],
       [ 93.5       ],
       [ 75.2417    ],
       [  7.75      ],
       [221.7792    ],
       [  7.225     ],
       [ 28.5       ],
       [  7.8542    ],
       [ 36.90913514],
       [134.5       ],
       [  7.7333    ],
       [136.7792    ],
       [164.8667    ],
       [  7.75      ],
       [ 13.        ],
       [ 36.75      ],
       [ 14.4583    ],
       [211.5       ],
       [  8.6625    ],
       [  7.8958    ],
       [  7.2292    ],
       [ 21.        ],
       [211.5       ],
       [ 27.7208    ],
       [ 26.        ],
       [  9.5       ],
       [ 83.1583    ],
       [  7.75      ],
       [ 79.2       ],
       [ 51.4792    ],
       [ 55.4417    ],
       [ 26.55      ],
       [  8.05      ],
       [ 46.9       ],
       [  9.35      ],
       [ 13.9       ],
       [  8.05      ],
       [ 13.8583    ],
       [262.375     ],
       [  7.7792    ],
       [ 26.        ],
       [ 32.5       ],
       [  7.6292    ],
       [ 69.55      ],
       [  8.05      ],
       [ 26.55      ],
       [ 83.1583    ],
       [  7.8958    ],
       [  7.225     ],
       [  7.775     ],
       [221.7792    ],
       [ 13.        ],
       [ 23.        ],
       [ 34.375     ],
       [ 20.25      ],
       [ 26.55      ],
       [ 13.        ],
       [ 13.        ],
       [247.5208    ],
       [ 23.        ],
       [ 10.5       ],
       [  7.        ],
       [ 22.025     ],
       [  8.05      ],
       [  7.55      ],
       [ 52.        ],
       [263.        ],
       [  7.75      ],
       [  7.25      ],
       [ 78.85      ],
       [ 26.        ],
       [262.375     ],
       [  7.925     ],
       [  7.775     ],
       [ 28.5375    ],
       [ 61.3792    ],
       [  8.6625    ],
       [ 26.55      ],
       [ 57.75      ],
       [  7.7958    ],
       [227.525     ],
       [ 53.1       ],
       [ 42.4       ],
       [  7.8958    ],
       [  9.325     ],
       [106.425     ],
       [ 23.45      ],
       [ 15.7417    ],
       [211.5       ],
       [ 16.1       ],
       [ 51.8625    ],
       [ 13.        ],
       [  7.8792    ],
       [ 73.5       ],
       [ 15.1       ],
       [ 65.        ],
       [ 32.5       ],
       [ 59.4       ],
       [  7.8542    ],
       [  7.75      ],
       [  7.8542    ],
       [ 45.5       ],
       [ 71.2833    ],
       [ 21.6792    ],
       [  8.05      ],
       [  9.5       ],
       [ 26.        ],
       [ 20.2125    ],
       [ 16.        ],
       [ 14.4542    ],
       [ 31.6792    ],
       [ 83.1583    ],
       [ 41.5792    ],
       [ 26.55      ],
       [ 15.2458    ],
       [  7.225     ],
       [ 16.7       ],
       [ 60.        ],
       [  6.95      ],
       [ 59.4       ],
       [ 21.        ],
       [  7.8792    ],
       [ 31.3875    ],
       [ 63.3583    ],
       [ 13.        ],
       [ 21.        ],
       [  7.225     ],
       [ 31.3875    ],
       [  8.1125    ],
       [  7.775     ],
       [  7.75      ],
       [  9.6875    ],
       [  6.4958    ],
       [ 14.4542    ],
       [ 15.75      ],
       [ 27.4458    ],
       [ 31.5       ],
       [ 13.775     ],
       [ 23.25      ],
       [ 13.        ],
       [  7.75      ],
       [  7.575     ],
       [  6.4375    ],
       [ 13.        ],
       [ 52.5542    ],
       [ 12.875     ],
       [ 21.        ],
       [ 14.4542    ],
       [134.5       ],
       [ 21.        ],
       [ 13.775     ],
       [ 82.2667    ],
       [  7.2292    ],
       [ 30.5       ],
       [  7.55      ],
       [262.375     ],
       [  7.8958    ],
       [  7.25      ],
       [  8.05      ],
       [  7.7958    ],
       [ 15.0333    ],
       [ 27.7208    ],
       [135.6333    ],
       [  7.775     ],
       [ 39.        ],
       [ 26.55      ],
       [ 39.        ],
       [  7.75      ],
       [  7.75      ],
       [  9.5       ],
       [  7.2292    ],
       [ 12.2875    ],
       [  7.75      ],
       [ 81.8583    ],
       [ 55.4417    ],
       [  7.7958    ],
       [  7.8792    ],
       [ 26.        ],
       [  7.225     ],
       [  7.8542    ],
       [  7.2292    ],
       [ 42.5       ],
       [ 13.5       ],
       [  7.75      ],
       [ 20.575     ],
       [  7.55      ],
       [ 15.5       ],
       [ 13.8625    ],
       [  7.225     ],
       [ 11.5       ],
       [ 65.        ],
       [ 17.4       ],
       [  7.2292    ],
       [ 13.5       ],
       [ 26.        ],
       [  8.05      ],
       [  7.75      ],
       [  7.8542    ],
       [ 13.        ],
       [  7.2292    ],
       [262.375     ],
       [  7.775     ],
       [ 61.175     ],
       [221.7792    ],
       [ 13.4167    ],
       [ 16.1       ],
       [ 69.55      ],
       [  7.8792    ],
       [ 10.5       ],
       [ 37.0042    ],
       [ 75.25      ],
       [ 10.5       ],
       [ 73.5       ],
       [  7.8958    ],
       [  7.8792    ],
       [  7.925     ],
       [  7.7208    ],
       [ 14.5       ],
       [  8.6625    ],
       [  8.6625    ],
       [ 14.4       ],
       [ 15.2458    ],
       [ 13.        ],
       [164.8667    ],
       [ 26.        ],
       [ 14.1083    ],
       [  7.775     ],
       [ 22.525     ],
       [263.        ],
       [  7.        ],
       [ 15.9       ],
       [ 15.2458    ],
       [ 25.7417    ],
       [ 57.75      ],
       [ 12.1833    ],
       [  7.775     ],
       [  7.2292    ],
       [ 23.        ],
       [  7.65      ],
       [ 12.7375    ],
       [ 30.        ],
       [ 26.        ],
       [  7.7333    ],
       [  7.75      ],
       [ 15.5       ],
       [ 50.4958    ],
       [ 26.        ],
       [ 90.        ],
       [  7.8958    ],
       [151.55      ],
       [ 21.        ],
       [ 31.5       ],
       [  7.8875    ],
       [ 15.5792    ],
       [  8.6625    ],
       [ 60.        ],
       [ 31.3875    ],
       [ 13.        ],
       [  7.25      ],
       [  8.05      ],
       [  8.9625    ],
       [ 16.1       ],
       [ 76.2917    ],
       [ 14.5       ],
       [  7.8542    ],
       [136.7792    ],
       [  3.1708    ],
       [  7.75      ],
       [  7.7333    ],
       [ 10.5       ],
       [ 26.        ],
       [ 65.        ],
       [ 81.8583    ],
       [512.3292    ],
       [  8.05      ],
       [ 93.5       ],
       [ 26.        ],
       [  8.05      ],
       [  7.8958    ],
       [ 15.55      ],
       [  8.05      ],
       [  0.        ],
       [  8.05      ],
       [ 36.75      ],
       [  7.775     ],
       [  7.75      ],
       [ 22.3583    ],
       [ 59.4       ],
       [ 69.55      ],
       [  7.8958    ],
       [  7.8208    ],
       [ 75.2417    ],
       [ 13.5       ],
       [  7.75      ]])

In [22]:
ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex=ohe_sex.fit_transform(X_train[["Sex"]])
X_train_embarked=ohe_embarked.fit_transform(X_train[["Embarked"]])
print(X_train_sex[3:15,0:2])
print(X_train_sex.shape)
X_test_sex=ohe_sex.transform(X_test[['Sex']])
X_test_embarked=ohe_embarked.transform(X_test[['Embarked']])
print(X_train_embarked.shape)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
(334, 2)
(334, 3)

In [23]:
X_train_rem=X_train.drop(columns=['Fare','Sex','Embarked'])
print(X_train_rem.shape)
X_test_rem=X_test.drop(columns=['Fare','Sex','Embarked'])

(334, 4)

In [24]:
X_train_transformed=np.concatenate((X_train_rem,X_train_fare,X_train_embarked,X_train_sex),axis=1)
X_test_transformed=np.concatenate((X_test_rem,X_test_fare,X_test_embarked,X_test_sex),axis=1)
X_train_transformed

array([[ 2., 32.,  0., ...,  1.,  0.,  1.],
       [ 2., 24.,  2., ...,  1.,  0.,  1.],
       [ 2., nan,  0., ...,  0.,  0.,  1.],
       ...,
       [ 1., 46.,  0., ...,  0.,  0.,  1.],
       [ 2., 24.,  0., ...,  1.,  0.,  1.],
       [ 3., nan,  0., ...,  0.,  0.,  1.]])

In [171]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transformed,Y_train)

DecisionTreeClassifier()

In [172]:
y_pred=clf.predict(X_test_transformed)
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [175]:
accuracy=accuracy_score(Y_test,y_pred)
accuracy

1.0

In [176]:
import pickle

In [179]:
pickle.dump(ohe_sex,open('model/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('model/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('model/clf.pkl','wb'))