In [27]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.impute import KNNImputer,SimpleImputer

In [28]:
data=pd.read_csv("train.csv")[["Pclass","Age","Survived","Fare"]]
data

     Pclass   Age  Survived     Fare
0         3  22.0         0   7.2500
1         1  38.0         1  71.2833
2         3  26.0         1   7.9250
3         1  35.0         1  53.1000
4         3  35.0         0   8.0500
..      ...   ...       ...      ...
886       2  27.0         0  13.0000
887       1  19.0         1  30.0000
888       3   NaN         0  23.4500
889       1  26.0         1  30.0000
890       3  32.0         0   7.7500

[891 rows x 4 columns]

In [29]:
data.describe()
data.isnull().sum()
data.isnull().mean()*100

Pclass       0.00000
Age         19.86532
Survived     0.00000
Fare         0.00000
dtype: float64

In [30]:
X=data.drop(columns=["Survived"])
Y=data["Survived"]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
X_test

     Pclass   Age     Fare
709       3   NaN  15.2458
439       2  31.0  10.5000
840       3  20.0   7.9250
720       2   6.0  33.0000
39        3  14.0  11.2417
..      ...   ...      ...
433       3  17.0   7.1250
773       3   NaN   7.2250
25        3  38.0  31.3875
84        2  17.0  10.5000
10        3   4.0  16.7000

[179 rows x 3 columns]

In [47]:
Knn=KNNImputer(n_neighbors=4,weights='distance')
X_train_trf=Knn.fit_transform(X_train)
X_test_trf=Knn.transform(X_test)

In [48]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

     Pclass   Age      Fare
0       1.0  45.5   28.5000
1       2.0  23.0   13.0000
2       3.0  32.0    7.9250
3       3.0  26.0    7.8542
4       3.0   6.0   31.2750
..      ...   ...       ...
707     3.0  21.0    7.6500
708     1.0  41.5   31.0000
709     3.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [ ]:
lr=LogisticRegression()
lr.fit(X_train_trf,Y_train)
y_pred=lr.predict(X_test_trf)
accuracy_score(Y_test,y_pred)

0.7374301675977654

: